// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rslvgeugmdihgkvtmopi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJzbHZnZXVnbWRpaGdrdnRtb3BpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA2ODM1NjYsImV4cCI6MjA2NjI1OTU2Nn0.yW7w6HezXwtl11QoWbD8hhI7gITVNByWXTQDsr-20XA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);